name: Adapter Health Check

on:
  # Run on push to main branch
  push:
    branches: [ main, master ]
  
  # Run on pull requests
  pull_request:
    branches: [ main, master ]
  
  # Run on schedule (daily at 00:00 UTC)
  schedule:
    - cron: '0 0 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      addresses:
        description: 'Comma-separated test addresses (optional)'
        required: false
        default: ''
      verbose:
        description: 'Enable verbose output'
        required: false
        type: boolean
        default: false

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-
      
      - name: Run adapter health check
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ -n "${{ github.event.inputs.addresses }}" ]; then
            # Use addresses from manual trigger
            IFS=',' read -ra ADDR <<< "${{ github.event.inputs.addresses }}"
            ADDRESSES="${ADDR[@]}"
          else
            # Use default test addresses
            ADDRESSES="0x3c2573b002cf51e64ab6d051814648eb3a305363 0x0a66d5927ffc0ee2e38a15f16f8949e697c4f439"
          fi
          
          VERBOSE_FLAG=""
          if [ "${{ github.event.inputs.verbose }}" = "true" ]; then
            VERBOSE_FLAG="--verbose"
          fi
          
          deno run -A check-adapters.ts $ADDRESSES $VERBOSE_FLAG
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: adapter-health-check-results
          path: |
            check-adapters.log
          retention-days: 30
          if-no-files-found: ignore
